[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.6.1"
config = "0.13.3"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.7"
argon2 = "0.5.0"