[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features=["json"]}
deadpool-postgres = { version = "0.10.5" }
#rocket_db_pools = { version = "0.1.0-rc.3", features = ["deadpool_postgres"]}
tokio-postgres = "0.7.8"
argon2 = "0.5.0"
uuid = { version = "1.3.0", features = ["v4"]}
dotenv = "0.15.0"
lazy_static = "1.4.0"
regex = "1.7.3"
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
tracing-tracy = {version = "0.10.2", features = ["system-tracing", "enable", "broadcast", "system-tracing"] }

