[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1"}
rocket_db_pools = { version = "0.1.0-rc.3", features = ["deadpool_postgres"]}
tokio-postgres = "0.7.8"
config = "0.13.3"
lazy_static = "1.4.0"

