[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc", features= ["secrets", "json", "uuid"]} 
uuid = { version = "1.3.0", features= ["v1", "v4"]} 
config = "0.13.3"
tokio = { version = "1.26.0", features = ["full"] }
tokio-postgres = "0.7.7"
deadpool-postgres = "0.10.5"
argon2 = "0.5.0"
regex = {version = "1.7.3", features = ["std"]}